//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM06660
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public bool GENDER { get; set; }
        public string HOMETOWN { get; set; }
    }
}
